feat: create teacher domain
Sexy-Sisters/TOJ-server-v2 pull request #83
Opened 2022-12-14 22:47 UTC by nswon

2022-12-14 23:12 UTC, leekyukin commented
도메인만 올리지 말고 기능 개발도 이 브렌치에 모아서 올려주세요 🤗

2022-12-14 23:12 UTC, leekyukin commented
오른쪽에 pr 셋팅도 해주세요!

2022-12-14 23:16 UTC, leekyukin requested changes

2022-12-14 23:16 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +
공백 지워주세요!

2022-12-14 23:16 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +    val student: Student? = null
우리 로직에서 생성한 학생정보는 필요가 없습니다.
학교랑 선생님이랑 N:1 관계 맺어 주셔야 합니다.

2022-12-14 23:16 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
> +    @OneToMany(mappedBy = "student", cascade = arrayOf(CascadeType.ALL))
`arrayOf()` 말고 `[ ]`(대괄호)로 바꿔도 됩니다!

2022-12-14 23:19 UTC, nswon commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +
넵

2022-12-14 23:21 UTC, nswon commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +    val student: Student? = null
학교에 가입한 학생들이 여러 선생님을 만들 수 있는 건가요?

2022-12-14 23:22 UTC, nswon commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
> +    @OneToMany(mappedBy = "student", cascade = arrayOf(CascadeType.ALL))
java에서는 ```cascade = CascadeType.ALL``` 로 바로 사용이 가능한데, 코틀린에서는 선언이 되지 않았습니다.  arrayOf와 대괄호의 용도가 궁금합니다. 단순히 타입을 여러개 받는다는 뜻인가요?

2022-12-14 23:29 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +    val student: Student? = null
맞습니다. 그런데 선생님한테 생성한 학생의 정보는 필요 없어요. 학교에 속한 선생님이 여러 명이라고 생각하시면 좋을 것 같아요.

2022-12-14 23:30 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
> +    @OneToMany(mappedBy = "student", cascade = arrayOf(CascadeType.ALL))
지금 한 번 알아보겠습니다!

2022-12-15 01:03 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
>      val teachers = mutableListOf<Teacher>()
이건 그냥 논의 해봐야 될것 같은데 연관관계 리스트 이름으로 `xxxList`가 좋을까요 `xxxs`가 좋을까요?

2022-12-15 01:06 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
> +    @OneToMany(mappedBy = "student", cascade = arrayOf(CascadeType.ALL))
원래 `cascade`에 속성값 여러개 설정이 가능합니다. 근데 자바의 경우 값이 하나라면 `{}`를 생략 가능하지만 코틀린은 문법상 `[]`를 꼭 달아야 한다고 합니다

2022-12-15 01:15 UTC, nswon commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
>      val teachers = mutableListOf<Teacher>()
자바 컨벤션에서는 변수명에 List, Collection 등 자료형 대신 복수형으로 나타내는 것이 좋다고 합니다. 자료형을 쓰지 않아도 충분히 의도를 드러낼 수 있기 때문입니다!

2022-12-15 01:17 UTC, nswon commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
> +    @OneToMany(mappedBy = "student", cascade = arrayOf(CascadeType.ALL))
오 감사합니다! 자바도 명시적으로 붙여주는게 있었다는 걸 처음 알았네요.

2022-12-15 01:18 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +}
`Always-Valid domain` 법칙에 따라서 항상 유효한 모메인이 되도록 생성하기 전에 `String`이 빈 값인지 체크 해주세요 🤗 참고로 `init{}`  사용해보세요!

2022-12-15 01:19 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/student/Student.kt
>      val teachers = mutableListOf<Teacher>()
그럼 그렇게 하도록 하죠!

2022-12-15 01:57 UTC, nswon commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +}
넵

2022-12-15 02:13 UTC, leekyukin commented
그냥 여기는 도메인만 하고 새로 브렌치 파서 개발합시다. 너무 복잡하겠네요

2022-12-15 02:14 UTC, leekyukin approved these changes

2022-12-15 02:14 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +    }
이때까지 `org.apache.commons.lang3`의 `StringUtils.isEmpty()` 사용했었는데 제 코드 고쳐야 겠네요 ㅠㅠ

2022-12-15 02:14 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +    }
굿잡입니다 👍🏿

2022-12-15 02:15 UTC, nswon commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +    }
👍👍👍

2022-12-15 02:17 UTC, leekyukin commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +    }
보니까 `isBlank()`가 더 어울릴것 같아요. 수정 부탁드립니다.

2022-12-15 02:21 UTC, nswon commented on src/main/kotlin/com/sexysisters/tojserverv2/domain/teacher/Teacher.kt
> +    }
넵!

2022-12-15 02:28 UTC, leekyukin approved these changes

2022-12-15 02:29 UTC, leekyukin commented
굿!! 머지해도 좋습니다

2022-12-15 02:30 UTC, merged